#!/bin/bash
./get_schema http://publications.aston.ac.uk/ &
./get_schema http://eprints.cardiff.ac.uk/ &
./get_schema http://create.canterbury.ac.uk/ &
./get_schema http://clok.uclan.ac.uk/ &
./get_schema http://openaccess.city.ac.uk/ &
./get_schema https://eprints.soton.ac.uk/ &
./get_schema http://repository.falmouth.ac.uk/ &
./get_schema http://irep.ntu.ac.uk/ &
./get_schema http://eprints.keele.ac.uk/ &
./get_schema http://kar.kent.ac.uk/ &
./get_schema http://eprints.kingston.ac.uk/ &
./get_schema http://researchonline.ljmu.ac.uk/ &
./get_schema http://eprints.mdx.ac.uk/ &
./get_schema http://eprints.nottingham.ac.uk/ &
./get_schema http://ray.yorksj.ac.uk/ &
./get_schema http://researchspace.bathspa.ac.uk/ &
./get_schema http://roar.uel.ac.uk/ &
./get_schema http://shura.shu.ac.uk/ &
./get_schema http://sure.sunderland.ac.uk/ &
./get_schema http://epubs.surrey.ac.uk/ &
./get_schema http://sro.sussex.ac.uk/ &
./get_schema http://uir.ulster.ac.uk/ &
./get_schema ttps://eprints.glos.ac.uk/ &
./get_schema http://eprints.lincoln.ac.uk/ &
./get_schema http://usir.salford.ac.uk/ &
./get_schema https://strathprints.strath.ac.uk/ &
./get_schema http://eprints.worc.ac.uk/ &
./get_schema http://wrap.warwick.ac.uk/ &
./get_schema http://eprints.whiterose.ac.uk/ &
wait
echo "Done!!!"
