#!/bin/bash

#bash script which will perform a full text + date search on a given list of EPrints repository URLs

#specify repo URLs
urls=(
http://eprints.hud.ac.uk/
)

#start and end date parameters
#start_date="2000"
#end_date="2018-01"

#search term
terms=(
algorithm
beautifulsoup
code
computation
computational
computed
computer
database
excel
fortran
gis
git
github
graphics
hpc
imagej
matlab
matplotlib
model
modeling
modelling
numpy
nvivo
'open-source'
pipeline
python
quantitative
regression
scrapy
scipy
simulated
simulation
software
spss
sqlalchemy
stata
statistical
supercomputing
visualisation
visualization
Rcpp
ggplot2
plyr
stringr
reshape2
RColorBrewer
workflow
wxpython
)

#regular expression to check the url
re="https?://([^/]+)/"

for t in "${terms[@]}"
do

	#loop through the URLs
	for i in "${urls[@]}"
	do
		if [[ $i =~ $re ]]; #matches the regex
		then
	
			#search string with parameters
			search="cgi/search/advanced?output=XML&_action_export_redir=Export&screen=Search&dataset=archive&exp=0%7C1%7C-date%7Carchive%7C-%7Cdocuments%3Adocuments%3AALL%3AIN%3A"$t"%7C-%7Ceprint_status%3Aeprint_status%3AANY%3AEQ%3Aarchive%7Cmetadata_visibility%3Ametadata_visibility%3AANY%3AEQ%3Ashow"

        		cache="./cache_all/"${BASH_REMATCH[1]}"/"$t".xml" #create location to store results
			export_url=$i$search #create export URL from repo URL and search parameteres	

			echo $export_url

			#retrieve the contents of the export
			wget -q -P ./ $export_url -O $cache &
			#mv $cache.tmp $cache

			#reassure user progress is being made
			echo "Processing: "$i
		fi
	done
	wait
	echo "Processed: "$t
done

exit 0


